In [1]:
import numpy as np

In [2]:
mylist = [1,2,3,4,5]

In [3]:
arr = np.array(mylist)

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
arr.shape

(5,)

In [7]:
mylist1 = [1,2,3,4,5]
mylist2 = [6,7,9,8,2]
mylist3 = [3,4,5,1,0]

In [11]:
arr = np.array([mylist1, mylist2, mylist3])

In [12]:
arr

array([[1, 2, 3, 4, 5],
       [6, 7, 9, 8, 2],
       [3, 4, 5, 1, 0]])

In [13]:
arr.shape

(3, 5)

In [14]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 9, 8],
       [2, 3, 4],
       [5, 1, 0]])

In [17]:
arr.reshape(3,5)

array([[1, 2, 3, 4, 5],
       [6, 7, 9, 8, 2],
       [3, 4, 5, 1, 0]])

In [18]:
arr[1:2,1:3]

array([[7, 9]])

In [19]:
arr[1:2,1:4]

array([[7, 9, 8]])

In [20]:
arr = np.arange(0,10)

In [21]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr = np.arange(0,10,2)
arr

array([0, 2, 4, 6, 8])

In [23]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [24]:
#copy function and broad casting 
arr[3:] = 100

In [25]:
arr

array([  0,   2,   4, 100, 100])

In [32]:
arr = np.arange(0,10)

In [33]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
arr1 = arr

In [35]:
arr1[3:] = 500

In [36]:
arr

array([  0,   1,   2, 500, 500, 500, 500, 500, 500, 500])

In [37]:
arr1

array([  0,   1,   2, 500, 500, 500, 500, 500, 500, 500])

In [38]:
#copy function
arr1 = arr.copy() #It is use to copy an array without replicating in first array

In [39]:
arr1[3:] = 100

In [42]:
print(arr1)
print(arr) #value not replicate or change in first array

[  0   1   2 100 100 100 100 100 100 100]
[  0   1   2 500 500 500 500 500 500 500]


In [43]:
print(arr<10) #print boolean value 
print(arr[arr<10])  # print vaue 

[ True  True  True False False False False False False False]
[0 1 2]


In [44]:
np.ones(4, int) #print ones in one dimension

array([1, 1, 1, 1])

In [46]:
np.ones((2,5),float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [47]:
#random Distibution
np.random.rand(3,3)   #normal distribution

array([[0.82313184, 0.04943924, 0.41920107],
       [0.43282419, 0.07463392, 0.71099375],
       [0.77527597, 0.61884281, 0.2916818 ]])

In [48]:
np.random.randn(4,4) #standard normal ditribition

array([[ 0.33309732,  1.33084031, -0.88418587, -0.67487527],
       [-0.5841989 , -0.09359303, -0.10522163, -1.04730864],
       [-0.88630254,  0.3125472 ,  0.21528346, -0.20159571],
       [-1.77039262,  0.09948944, -1.03565949, -0.40997381]])

In [49]:
np.random.randint(0,100,8)

array([85, 39, 55, 92,  7,  2, 67, 33])